default:
  host: "0.0.0.0"
  port: 8068
  workers: 4
  log:
    level: "DEBUG"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    filename: 'log/llm_search_proxy.log'

  channels:
    - api_key: "example" # example 示例不会被载入
      azure_endpoint: "http://xxx"
      api_version: "2024-02-01"
      name: 'example1'     # 记录usage时 channel_name
      provider: "azure"
production:
  workers: 10
  log:
    level: "INFO"